/* <float.h> for MEOW: IEEE single and double, long double being double. */
#ifndef _PDCLIB_FLOAT_H
#define _PDCLIB_FLOAT_H _PDCLIB_FLOAT_H

#include "pdclib/_PDCLIB_config.h"

#define FLT_ROUNDS      _PDCLIB_FLT_ROUNDS
#define FLT_EVAL_METHOD _PDCLIB_FLT_EVAL_METHOD
#define FLT_HAS_SUBNORM _PDCLIB_FLT_HAS_SUBNORM
#define DBL_HAS_SUBNORM _PDCLIB_DBL_HAS_SUBNORM
#define LDBL_HAS_SUBNORM _PDCLIB_LDBL_HAS_SUBNORM
#define FLT_RADIX       _PDCLIB_FLT_RADIX
#define FLT_MANT_DIG    _PDCLIB_FLT_MANT_DIG
#define DBL_MANT_DIG    _PDCLIB_DBL_MANT_DIG
#define LDBL_MANT_DIG   _PDCLIB_LDBL_MANT_DIG
#define FLT_DECIMAL_DIG _PDCLIB_FLT_DECIMAL_DIG
#define DBL_DECIMAL_DIG _PDCLIB_DBL_DECIMAL_DIG
#define LDBL_DECIMAL_DIG _PDCLIB_LDBL_DECIMAL_DIG
#define DECIMAL_DIG     _PDCLIB_DECIMAL_DIG
#define FLT_DIG         _PDCLIB_FLT_DIG
#define DBL_DIG         _PDCLIB_DBL_DIG
#define LDBL_DIG        _PDCLIB_LDBL_DIG
#define FLT_MIN_EXP     _PDCLIB_FLT_MIN_EXP
#define DBL_MIN_EXP     _PDCLIB_DBL_MIN_EXP
#define LDBL_MIN_EXP    _PDCLIB_LDBL_MIN_EXP
#define FLT_MIN_10_EXP  _PDCLIB_FLT_MIN_10_EXP
#define DBL_MIN_10_EXP  _PDCLIB_DBL_MIN_10_EXP
#define LDBL_MIN_10_EXP _PDCLIB_LDBL_MIN_10_EXP
#define FLT_MAX_EXP     _PDCLIB_FLT_MAX_EXP
#define DBL_MAX_EXP     _PDCLIB_DBL_MAX_EXP
#define LDBL_MAX_EXP    _PDCLIB_LDBL_MAX_EXP
#define FLT_MAX_10_EXP  _PDCLIB_FLT_MAX_10_EXP
#define DBL_MAX_10_EXP  _PDCLIB_DBL_MAX_10_EXP
#define LDBL_MAX_10_EXP _PDCLIB_LDBL_MAX_10_EXP
#define FLT_MAX         _PDCLIB_FLT_MAX
#define DBL_MAX         _PDCLIB_DBL_MAX
#define LDBL_MAX        _PDCLIB_LDBL_MAX
#define FLT_EPSILON     _PDCLIB_FLT_EPSILON
#define DBL_EPSILON     _PDCLIB_DBL_EPSILON
#define LDBL_EPSILON    _PDCLIB_LDBL_EPSILON
#define FLT_MIN         _PDCLIB_FLT_MIN
#define DBL_MIN         _PDCLIB_DBL_MIN
#define LDBL_MIN        _PDCLIB_LDBL_MIN
#define FLT_TRUE_MIN    _PDCLIB_FLT_TRUE_MIN
#define DBL_TRUE_MIN    _PDCLIB_DBL_TRUE_MIN
#define LDBL_TRUE_MIN   _PDCLIB_LDBL_TRUE_MIN

#endif
